### PR TITLE
Fix homepage title tag

### PR DESCRIPTION
**Pull request by rudimocnik**
Google search query for `dydx docs` listed a search result with a title `docs? dYdX Trading's` pointing to `https://docs.dydx.trade/`
Screenshot 2024-08-20 at 00 42 34

This is likely due to generic "Index" header tag no the homepage that Google search engine doesn't [like](https://developers.google.com/search/docs/appearance/title-link). The changes below set a more specific and descriptive header tag "dYdX Trading's Docs" and add an additional description meta tag.
 Screenshot 2024-08-20 at 00 46 05

Here is the local build with the new tags:
Screenshot 2024-08-20 at 00 44 41

Further, pinning dependency was to handle VERCEL build error:

ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @tanstack/virtual-core@3.10.0
This error happened while installing the dependencies of nextra@2.13.4

### CODE REVIEW

**Comment by pswies** [comment]
Shouldn't the `virtual-core` issue be handled in the upstream?

**Comment by rudimocnik** [comment]
> Shouldn't the `virtual-core` issue be handled in the upstream?

Ideally, yes. I can open a PR for the relevant commit. Still, I'd suggest to merge this entire PR for the sake of deploying the fix to the issue described above. w/o it Vercel build fails as dependencies try to install a version of tanstack/virtual-core that doesn't exist. I just noticed, a [version 3.10.1](https://www.npmjs.com/package/@tanstack/virtual-core) was released while some dependency in our build requires 3.10 which does not exist.

**Comment by pswies** [comment]
Gotcha. 👍 
Afterwards, please create a PR for the upstream.

**Review by pswies — APPROVED** [review]
LGTM

**Pull request merged**
